### ISSUE TITLE
docker.errors.BuildError on RoBERTa

### ISSUE THREAD

**Issue by pmbaumgartner** [RTIInternational/gobbli#11]
## System Information
- OS platform and distribution (e.g. Linux Ubuntu 16.04): Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-159-generic x86_64)
- gobbli version: gobbli==0.0.6
- Python version: 3.7
- Other information relevant to the problem (GPU model, Docker version, etc):

## Description

I'm trying to use RoBERTa and the model fails to build. It looks like it's missing a required file for the build based on the traceback. Existing code:

```
clf = Transformer(
        transformer_model="Roberta",
        transformer_weights="roberta-base",
        max_seq_length=256,
        use_gpu=True,
        nvidia_visible_devices="0,1,2"
        )

# Set up classifier resources -- Docker image, etc.
clf.build()
```

Traceback:
```
Traceback (most recent call last):
  File "train_predict_roberta.py", line 62, in <module>
    clf.build()
  File "/home/pbaumgartner/anaconda3/envs/gobbli-cdc/lib/python3.7/site-packages/gobbli/model/base.py", line 221, in build
    self._build()
  File "/home/pbaumgartner/anaconda3/envs/gobbli-cdc/lib/python3.7/site-packages/gobbli/model/transformer/model.py", line 106, in _build
    **self._base_docker_build_kwargs,
  File "/home/pbaumgartner/anaconda3/envs/gobbli-cdc/lib/python3.7/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: COPY failed: stat /data/lib/docker2/tmp/docker-builder753006786/src/requirements.txt: no such file or directory
```
## Code for Minimal Reproducible Example

see above

## Output

see above

**Comment by jasonnance** [comment]
Yep, thanks for the report.  This is another issue with the PyPI-installed version.  We were still missing a file required for the build from the PyPI upload.

Should be fixed in v0.0.7.
